const menu = [
    // sushis
    {
        foodName: "Dragon Roll",
        category: "Main Dish",
        chefRec: "Yes",
        specialty: "Yes",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    {
        foodName: "California Roll",
        category: "Main Dish",
        chefRec: "Yes",
        specialty: "No",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    {
        foodName: "Spicy Tuna Roll",
        category: "Main Dish",
        chefRec: "No",
        specialty: "Yes",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    {
        foodName: "Spicy Salmon Roll",
        category: "Main Dish",
        chefRec: "No",
        specialty: "Yes",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    {
        foodName: "Eel Avocado Roll",
        category: "Main Dish",
        chefRec: "Yes",
        specialty: "Yes",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    {
        foodName: "Shrimp Tempura Roll",
        category: "Main Dish",
        chefRec: "Yes",
        specialty: "No",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    // ramens
    {
        foodName: "Tonkotsu Ramen",
        category: "Main Dish",
        chefRec: "No",
        specialty: "No",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    {
        foodName: "Spicy Kimchi Ramen",
        category: "Main Dish",
        chefRec: "Yes",
        specialty: "Yes",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    {
        foodName: "Classic Shoyu Ramen",
        category: "Main Dish",
        chefRec: "No",
        specialty: "Yes",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    //sandwiches
    {
        foodName: "California Sandwich",
        category: "Sandwich",
        chefRec: "Yes",
        specialty: "No",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    {
        foodName: "Katsu Chicken Sandwich",
        category: "Sandwich",
        chefRec: "Yes",
        specialty: "Yes",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    {
        foodName: "Turkey Sandwich",
        category: "Sandwich",
        chefRec: "No",
        specialty: "No",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    // salads
    {
        foodName: "Avocado Salad",
        category: "Salad",
        chefRec: "Yes",
        specialty: "No",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    {
        foodName: "Kani Salad",
        category: "Salad",
        chefRec: "No",
        specialty: "No",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
    {
        foodName: "Caesar Salad",
        category: "Salad",
        chefRec: "No",
        specialty: "No",
        dessert: "No",
        alcBev: "No",
        nonalc: "No",
    },
]
