export const menu = [
    // sushis
    {
        foodName: "Dragon Roll",
        category: "Special",
        price: 14.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: true,
        dessert: false,
        image: "https://foreignfork.com/wp-content/uploads/2023/05/DragonRoll-FEATURE.jpg",
      },
      {
        foodName: "Rainbow Roll",
        category: "Special",
        price: 16.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Spicy Tuna Roll",
        category: "Appetizers",
        price: 8.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: true,
        kids: false,
        chefsRec: false,
        dessert: false,
        image: "https://129655557.cdn6.editmysite.com/uploads/1/2/9/6/129655557/s236665495549630432_p176_i5_w4032.jpeg?width=2400&optimize=medium",
      },
      {
        foodName: "California Roll",
        category: "Appetizers",
        price: 7.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: true,
        kids: false,
        chefsRec: false,
        dessert: false,
        image: "https://www.justonecookbook.com/wp-content/uploads/2022/12/California-Roll-6126-I-2.jpg",
      },
      {
        foodName: "Miso Soup",
        category: "Soup",
        price: 4.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: true,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
    // ramens
    {
        foodName: "Classic Shoyu Ramen",
        category: "Main Dishes",
        price: 11.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: true,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Spicy Miso Ramen",
        category: "Main Dishes",
        price: 13.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: true,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Vegetarian Shoyu Ramen",
        category: "Main Dishes",
        price: 10.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: true,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
    //sandwiches
    {
        foodName: "California Sandwich",
        category: "Main Dishes",
        price: 9.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Katsu Chicken Sandwich",
        category: "Main Dishes",
        price: 12.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Turkey Sandwich",
        category: "Main Dishes",
        price: 8.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      //salad
    {
        foodName: "Kani Salad",
        category: "Salads",
        price: 6.99,
        alcBev: false,
        nonAlc: false,
        salad: true,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Avocado Salad",
        category: "Salads",
        price: 8.99,
        alcBev: false,
        nonAlc: false,
        salad: true,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      //salads
      {
        foodName: "Caesar Salad",
        category: "Salads",
        price: 7.99,
        alcBev: false,
        nonAlc: false,
        salad: true,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
// side dishes
      {
        foodName: "Edamame",
        category: "Side Dishes",
        price: 4.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: true,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Agedashi Tofu",
        category: "Side Dishes",
        price: 6.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: true,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Takoyaki",
        category: "Side Dishes",
        price: 8.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: true,
        kids: false,
        chefsRec: true,
        dessert: false,
      },
      {
        foodName: "Gyoza",
        category: "Side Dishes",
        price: 7.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: true,
        kids: false,
        chefsRec: true,
        dessert: false,
      },
      {
        foodName: "Tempura",
        category: "Side Dishes",
        price: 9.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: true,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      // kids menu
      {
        foodName: "Kids' Bento Box",
        category: "Kids Menu",
        price: 9.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: true,
        kids: true,
        chefsRec: true,
        dessert: true,
      },
      {
        foodName: "Chicken Teriyaki Nuggets",
        category: "Kids Menu",
        price: 7.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: true,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Cheese Ramen",
        category: "Kids Menu",
        price: 6.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: true,
        appetizer: false,
        kids: true,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Vegetable Tempura Rice Bowl",
        category: "Kids Menu",
        price: 8.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: true,
        kids: true,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Mini Sushi Rolls",
        category: "Kids Menu",
        price: 10.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: true,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Fruit and Yogurt Parfait",
        category: "Kids Menu",
        price: 5.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: true,
        chefsRec: false,
        dessert: true,
      },
      //desserts
      {
        foodName: "Chocolate Lava Cake",
        category: "Desserts",
        price: 8.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: true,
      },
      {
        foodName: "Tiramisu",
        category: "Desserts",
        price: 9.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: true,
        dessert: true,
      },
      {
        foodName: "Mango Sticky Rice",
        category: "Desserts",
        price: 7.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: true,
      },
      {
        foodName: "Matcha Mochi",
        category: "Japanese Desserts",
        price: 6.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: true,
        dessert: true,
      },
      {
        foodName: "Dorayaki (Red Bean Pancake)",
        category: "Japanese Desserts",
        price: 5.99,
        alcBev: false,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: true,
      },
      //alcoholics
      {
        foodName: "Sake",
        category: "Alcoholic Beverages",
        price: 12.99,
        alcBev: true,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Japanese Whisky Highball",
        category: "Alcoholic Beverages",
        price: 14.99,
        alcBev: true,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Plum Wine (Ume-shu)",
        category: "Alcoholic Beverages",
        price: 10.99,
        alcBev: true,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Suntory Toki Highball",
        category: "Alcoholic Beverages",
        price: 16.99,
        alcBev: true,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Japanese Plum Soju",
        category: "Alcoholic Beverages",
        price: 11.99,
        alcBev: true,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Mai Tai",
        category: "Alcoholic Beverages",
        price: 15.99,
        alcBev: true,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Margarita",
        category: "Alcoholic Beverages",
        price: 13.99,
        alcBev: true,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Old Fashioned",
        category: "Alcoholic Beverages",
        price: 14.99,
        alcBev: true,
        nonAlc: false,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
//non alcohols
      {
        foodName: "Classic Lemonade",
        category: "Non-Alcoholic Beverages",
        price: 4.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Mango Tango Smoothie",
        category: "Non-Alcoholic Beverages",
        price: 5.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Matcha Latte",
        category: "Non-Alcoholic Beverages",
        price: 6.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Strawberry Bubble Tea",
        category: "Non-Alcoholic Beverages",
        price: 5.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Blueberry Mint Sparkler",
        category: "Non-Alcoholic Beverages",
        price: 6.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Pineapple Coconut Smoothie",
        category: "Non-Alcoholic Beverages",
        price: 5.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Honeydew Milk Tea",
        category: "Non-Alcoholic Beverages",
        price: 6.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Raspberry Lemonade",
        category: "Non-Alcoholic Beverages",
        price: 4.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Passion Fruit Iced Tea",
        category: "Non-Alcoholic Beverages",
        price: 5.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Watermelon Slush",
        category: "Non-Alcoholic Beverages",
        price: 6.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Peach Berry Smoothie",
        category: "Non-Alcoholic Beverages",
        price: 5.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Coca-Cola",
        category: "Non-Alcoholic Beverages",
        price: 2.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Pepsi",
        category: "Non-Alcoholic Beverages",
        price: 2.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
      {
        foodName: "Sprite",
        category: "Non-Alcoholic Beverages",
        price: 2.99,
        alcBev: false,
        nonAlc: true,
        salad: false,
        soup: false,
        appetizer: false,
        kids: false,
        chefsRec: false,
        dessert: false,
      },
]

